version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: neoassessment
      POSTGRES_PASSWORD: "Gp12YHmRUfYPJKqUuzJSDrN0l9tZvB73"
    volumes:
      - neoassessment_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "nfKfXI68RXAB1y-GqYoXFUAdv4r5g7-L"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  neoassessment_data:
